export function sanitizeString(input: string): string {
  if (typeof input !== 'string') return '';
  return input.trim();
}

export function unescapeHTMLEntities(input: string): string {
  if (typeof input !== 'string') return '';
  return input
    .replace(/&#x2F;/g, '/')
    .replace(/&#x5C;/g, '\\')
    .replace(/&#x60;/g, '`')
    .replace(/&#x27;/g, "'")
    .replace(/&quot;/g, '"')
    .replace(/&gt;/g, '>')
    .replace(/&lt;/g, '<')
    .replace(/&amp;/g, '&');
}

export function sanitizeEmail(input: string): string {
  if (typeof input !== 'string') return '';
  return input.trim().toLowerCase().replace(/[^a-z0-9@._+-]/g, '');
}

export function sanitizePhone(input: string): string {
  if (typeof input !== 'string') return '';
  return input.trim().replace(/[^0-9+()\-\s]/g, '');
}

export function sanitizeUrl(input: string): string {
  if (typeof input !== 'string') return '';
  const trimmed = input.trim();
  if (!trimmed) return '';

  // Data URLs are only accepted for images generated by the local uploader.
  if (/^data:/i.test(trimmed)) {
    return /^data:image\/(?:gif|jpe?g|png|webp|avif);base64,[a-z0-9+/]+=*$/i.test(trimmed)
      ? trimmed
      : '';
  }

  try {
    const baseUrl = typeof window !== 'undefined' ? window.location.origin : 'https://localhost';
    const parsed = new URL(trimmed, baseUrl);
    const isLocalHttp = parsed.protocol === 'http:' &&
      /^(localhost|127\.0\.0\.1|\[::1\])$/.test(parsed.hostname);

    if (parsed.protocol !== 'https:' && !isLocalHttp) return '';
    return parsed.href;
  } catch {
    return '';
  }
}

export function sanitizeObject<T extends Record<string, unknown>>(obj: T): T {
  if (Array.isArray(obj)) {
    return obj.map(item => {
      if (typeof item === 'string') return sanitizeString(item);
      if (typeof item === 'object' && item !== null) return sanitizeObject(item as Record<string, unknown>);
      return item;
    }) as unknown as T;
  }
  const sanitized: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(obj)) {
    if (typeof value === 'string') {
      sanitized[key] = sanitizeString(value);
    } else if (typeof value === 'object' && value !== null) {
      sanitized[key] = sanitizeObject(value as Record<string, unknown>);
    } else {
      sanitized[key] = value;
    }
  }
  return sanitized as T;
}
