ALTER TABLE bookings ADD COLUMN IF NOT EXISTS "reminderSent" BOOLEAN DEFAULT false;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS "reminderSentAt" TEXT DEFAULT '';
ALTER TABLE emailconfig ADD COLUMN IF NOT EXISTS "emailjsPrivateKey" TEXT DEFAULT '';
