-- =============================================================================
-- FIX: Restrict Storage RLS — remove public read from sensitive buckets
--
-- Before: All buckets (photographs, proofs, profile, seo, packages, 
--          session_categories) were publicly readable.
-- After:  Only 'photographs' remains public (portfolio display).
--         All other buckets require authentication (admin).
--         'proofs' bucket is also restricted — client gallery access
--         is done via signed URLs generated by the validate-gallery
--         Edge Function using service_role.
-- =============================================================================

-- 1. Drop existing permissive policies
DROP POLICY IF EXISTS "Public can read images" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated users can upload images" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated users can update images" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated users can delete images" ON storage.objects;

-- 2. Public read — ONLY for the 'photographs' bucket (portfolio display)
CREATE POLICY "Public read photographs bucket" ON storage.objects
  FOR SELECT
  TO public
  USING (bucket_id = 'photographs');

-- 3. Authenticated users (admin) can read all buckets
CREATE POLICY "Auth read all buckets" ON storage.objects
  FOR SELECT
  TO authenticated
  USING (bucket_id IN (
    'photographs', 'proofs', 'profile', 'seo', 
    'packages', 'session_categories'
  ));

-- 4. Authenticated upload
CREATE POLICY "Auth upload" ON storage.objects
  FOR INSERT
  TO authenticated
  WITH CHECK (bucket_id IN (
    'photographs', 'proofs', 'profile', 'seo', 
    'packages', 'session_categories'
  ));

-- 5. Authenticated update
CREATE POLICY "Auth update" ON storage.objects
  FOR UPDATE
  TO authenticated
  USING (bucket_id IN (
    'photographs', 'proofs', 'profile', 'seo', 
    'packages', 'session_categories'
  ))
  WITH CHECK (bucket_id IN (
    'photographs', 'proofs', 'profile', 'seo', 
    'packages', 'session_categories'
  ));

-- 6. Authenticated delete
CREATE POLICY "Auth delete" ON storage.objects
  FOR DELETE
  TO authenticated
  USING (bucket_id IN (
    'photographs', 'proofs', 'profile', 'seo', 
    'packages', 'session_categories'
  ));